#!/bin/ash
set -eux

while true; do
  /usr/bin/certbot \
    certonly \
    --standalone \
    --standalone-supported-challenges http-01 \
    --keep-until-expiring \
    --text \
    --agree-tos \
    --email $EMAIL \
    --domains $DOMAINS
  sleep 86400
done
